Feature: place toy robot

  toy robot should be able to be placed on a table
  all position out of the table should be ignored

  Scenario: placed at 00NORTH
    Given a table width 5
    When place at "0,0,NORTH"
    Then report as "0,0,NORTH"

  Scenario: placed at 11NORTH
    Given a table width 5
    When place at "1,1,NORTH"
    Then report as "1,1,NORTH"

  Scenario: replace after move from 00NORTH
    Given a table width 5
    When place at "0,0,NORTH"
    And manage to move
    And place at "0,0,NORTH"
    Then report as "0,0,NORTH"

  Scenario: replace after turn right from 00NORTH
    Given a table width 5
    When place at "0,0,NORTH"
    And turn right
    And place at "0,0,NORTH"
    Then report as "0,0,NORTH"

  Scenario: replace after turn left from 00NORTH
    Given a table width 5
    When place at "0,0,NORTH"
    And turn left
    And place at "0,0,NORTH"
    Then report as "0,0,NORTH"

  Scenario Outline: place at valid position
    Given a table width 5
    When place at "<position>"
    Then report as "<position>"
    Examples: all valid position
      | position |
      | 0,0,EAST |
      | 0,1,EAST |
      | 0,2,EAST |
      | 0,3,EAST |
      | 0,4,EAST |
      | 1,0,EAST |
      | 1,1,EAST |
      | 1,2,EAST |
      | 1,3,EAST |
      | 1,4,EAST |
      | 2,0,EAST |
      | 2,1,EAST |
      | 2,2,EAST |
      | 2,3,EAST |
      | 2,4,EAST |
      | 3,0,EAST |
      | 3,1,EAST |
      | 3,2,EAST |
      | 3,3,EAST |
      | 3,4,EAST |
      | 4,0,EAST |
      | 4,1,EAST |
      | 4,2,EAST |
      | 4,3,EAST |
      | 4,4,EAST |
      | 0,0,SOUTH |
      | 0,1,SOUTH |
      | 0,2,SOUTH |
      | 0,3,SOUTH |
      | 0,4,SOUTH |
      | 1,0,SOUTH |
      | 1,1,SOUTH |
      | 1,2,SOUTH |
      | 1,3,SOUTH |
      | 1,4,SOUTH |
      | 2,0,SOUTH |
      | 2,1,SOUTH |
      | 2,2,SOUTH |
      | 2,3,SOUTH |
      | 2,4,SOUTH |
      | 3,0,SOUTH |
      | 3,1,SOUTH |
      | 3,2,SOUTH |
      | 3,3,SOUTH |
      | 3,4,SOUTH |
      | 4,0,SOUTH |
      | 4,1,SOUTH |
      | 4,2,SOUTH |
      | 4,3,SOUTH |
      | 4,4,SOUTH |
      | 0,0,WEST |
      | 0,1,WEST |
      | 0,2,WEST |
      | 0,3,WEST |
      | 0,4,WEST |
      | 1,0,WEST |
      | 1,1,WEST |
      | 1,2,WEST |
      | 1,3,WEST |
      | 1,4,WEST |
      | 2,0,WEST |
      | 2,1,WEST |
      | 2,2,WEST |
      | 2,3,WEST |
      | 2,4,WEST |
      | 3,0,WEST |
      | 3,1,WEST |
      | 3,2,WEST |
      | 3,3,WEST |
      | 3,4,WEST |
      | 4,0,WEST |
      | 4,1,WEST |
      | 4,2,WEST |
      | 4,3,WEST |
      | 4,4,WEST |
      | 0,0,NORTH |
      | 0,1,NORTH |
      | 0,2,NORTH |
      | 0,3,NORTH |
      | 0,4,NORTH |
      | 1,0,NORTH |
      | 1,1,NORTH |
      | 1,2,NORTH |
      | 1,3,NORTH |
      | 1,4,NORTH |
      | 2,0,NORTH |
      | 2,1,NORTH |
      | 2,2,NORTH |
      | 2,3,NORTH |
      | 2,4,NORTH |
      | 3,0,NORTH |
      | 3,1,NORTH |
      | 3,2,NORTH |
      | 3,3,NORTH |
      | 3,4,NORTH |
      | 4,0,NORTH |
      | 4,1,NORTH |
      | 4,2,NORTH |
      | 4,3,NORTH |
      | 4,4,NORTH |

  Scenario Outline: place at invalid position
    Given a table width 5
    When try to place at "<position>"
    Then try to report
  Examples: all invalid x-axis
    | position |
    | -9,0,EAST |
    | -9,1,EAST |
    | -9,2,EAST |
    | -9,3,EAST |
    | -9,4,EAST |
    | -8,0,EAST |
    | -8,1,EAST |
    | -8,2,EAST |
    | -8,3,EAST |
    | -8,4,EAST |
    | -7,0,EAST |
    | -7,1,EAST |
    | -7,2,EAST |
    | -7,3,EAST |
    | -7,4,EAST |
    | -6,0,EAST |
    | -6,1,EAST |
    | -6,2,EAST |
    | -6,3,EAST |
    | -6,4,EAST |
    | -5,0,EAST |
    | -5,1,EAST |
    | -5,2,EAST |
    | -5,3,EAST |
    | -5,4,EAST |
    | -4,0,EAST |
    | -4,1,EAST |
    | -4,2,EAST |
    | -4,3,EAST |
    | -4,4,EAST |
    | -3,0,EAST |
    | -3,1,EAST |
    | -3,2,EAST |
    | -3,3,EAST |
    | -3,4,EAST |
    | -2,0,EAST |
    | -2,1,EAST |
    | -2,2,EAST |
    | -2,3,EAST |
    | -2,4,EAST |
    | -1,0,EAST |
    | -1,1,EAST |
    | -1,2,EAST |
    | -1,3,EAST |
    | -1,4,EAST |
    | 5,0,EAST |
    | 5,1,EAST |
    | 5,2,EAST |
    | 5,3,EAST |
    | 5,4,EAST |
    | 6,0,EAST |
    | 6,1,EAST |
    | 6,2,EAST |
    | 6,3,EAST |
    | 6,4,EAST |
    | 7,0,EAST |
    | 7,1,EAST |
    | 7,2,EAST |
    | 7,3,EAST |
    | 7,4,EAST |
    | 8,0,EAST |
    | 8,1,EAST |
    | 8,2,EAST |
    | 8,3,EAST |
    | 8,4,EAST |
    | 9,0,EAST |
    | 9,1,EAST |
    | 9,2,EAST |
    | 9,3,EAST |
    | 9,4,EAST |
    | -9,0,SOUTH |
    | -9,1,SOUTH |
    | -9,2,SOUTH |
    | -9,3,SOUTH |
    | -9,4,SOUTH |
    | -8,0,SOUTH |
    | -8,1,SOUTH |
    | -8,2,SOUTH |
    | -8,3,SOUTH |
    | -8,4,SOUTH |
    | -7,0,SOUTH |
    | -7,1,SOUTH |
    | -7,2,SOUTH |
    | -7,3,SOUTH |
    | -7,4,SOUTH |
    | -6,0,SOUTH |
    | -6,1,SOUTH |
    | -6,2,SOUTH |
    | -6,3,SOUTH |
    | -6,4,SOUTH |
    | -5,0,SOUTH |
    | -5,1,SOUTH |
    | -5,2,SOUTH |
    | -5,3,SOUTH |
    | -5,4,SOUTH |
    | -4,0,SOUTH |
    | -4,1,SOUTH |
    | -4,2,SOUTH |
    | -4,3,SOUTH |
    | -4,4,SOUTH |
    | -3,0,SOUTH |
    | -3,1,SOUTH |
    | -3,2,SOUTH |
    | -3,3,SOUTH |
    | -3,4,SOUTH |
    | -2,0,SOUTH |
    | -2,1,SOUTH |
    | -2,2,SOUTH |
    | -2,3,SOUTH |
    | -2,4,SOUTH |
    | -1,0,SOUTH |
    | -1,1,SOUTH |
    | -1,2,SOUTH |
    | -1,3,SOUTH |
    | -1,4,SOUTH |
    | 5,0,SOUTH |
    | 5,1,SOUTH |
    | 5,2,SOUTH |
    | 5,3,SOUTH |
    | 5,4,SOUTH |
    | 6,0,SOUTH |
    | 6,1,SOUTH |
    | 6,2,SOUTH |
    | 6,3,SOUTH |
    | 6,4,SOUTH |
    | 7,0,SOUTH |
    | 7,1,SOUTH |
    | 7,2,SOUTH |
    | 7,3,SOUTH |
    | 7,4,SOUTH |
    | 8,0,SOUTH |
    | 8,1,SOUTH |
    | 8,2,SOUTH |
    | 8,3,SOUTH |
    | 8,4,SOUTH |
    | 9,0,SOUTH |
    | 9,1,SOUTH |
    | 9,2,SOUTH |
    | 9,3,SOUTH |
    | 9,4,SOUTH |
    | -9,0,WEST |
    | -9,1,WEST |
    | -9,2,WEST |
    | -9,3,WEST |
    | -9,4,WEST |
    | -8,0,WEST |
    | -8,1,WEST |
    | -8,2,WEST |
    | -8,3,WEST |
    | -8,4,WEST |
    | -7,0,WEST |
    | -7,1,WEST |
    | -7,2,WEST |
    | -7,3,WEST |
    | -7,4,WEST |
    | -6,0,WEST |
    | -6,1,WEST |
    | -6,2,WEST |
    | -6,3,WEST |
    | -6,4,WEST |
    | -5,0,WEST |
    | -5,1,WEST |
    | -5,2,WEST |
    | -5,3,WEST |
    | -5,4,WEST |
    | -4,0,WEST |
    | -4,1,WEST |
    | -4,2,WEST |
    | -4,3,WEST |
    | -4,4,WEST |
    | -3,0,WEST |
    | -3,1,WEST |
    | -3,2,WEST |
    | -3,3,WEST |
    | -3,4,WEST |
    | -2,0,WEST |
    | -2,1,WEST |
    | -2,2,WEST |
    | -2,3,WEST |
    | -2,4,WEST |
    | -1,0,WEST |
    | -1,1,WEST |
    | -1,2,WEST |
    | -1,3,WEST |
    | -1,4,WEST |
    | 5,0,WEST |
    | 5,1,WEST |
    | 5,2,WEST |
    | 5,3,WEST |
    | 5,4,WEST |
    | 6,0,WEST |
    | 6,1,WEST |
    | 6,2,WEST |
    | 6,3,WEST |
    | 6,4,WEST |
    | 7,0,WEST |
    | 7,1,WEST |
    | 7,2,WEST |
    | 7,3,WEST |
    | 7,4,WEST |
    | 8,0,WEST |
    | 8,1,WEST |
    | 8,2,WEST |
    | 8,3,WEST |
    | 8,4,WEST |
    | 9,0,WEST |
    | 9,1,WEST |
    | 9,2,WEST |
    | 9,3,WEST |
    | 9,4,WEST |
    | -9,0,NORTH |
    | -9,1,NORTH |
    | -9,2,NORTH |
    | -9,3,NORTH |
    | -9,4,NORTH |
    | -8,0,NORTH |
    | -8,1,NORTH |
    | -8,2,NORTH |
    | -8,3,NORTH |
    | -8,4,NORTH |
    | -7,0,NORTH |
    | -7,1,NORTH |
    | -7,2,NORTH |
    | -7,3,NORTH |
    | -7,4,NORTH |
    | -6,0,NORTH |
    | -6,1,NORTH |
    | -6,2,NORTH |
    | -6,3,NORTH |
    | -6,4,NORTH |
    | -5,0,NORTH |
    | -5,1,NORTH |
    | -5,2,NORTH |
    | -5,3,NORTH |
    | -5,4,NORTH |
    | -4,0,NORTH |
    | -4,1,NORTH |
    | -4,2,NORTH |
    | -4,3,NORTH |
    | -4,4,NORTH |
    | -3,0,NORTH |
    | -3,1,NORTH |
    | -3,2,NORTH |
    | -3,3,NORTH |
    | -3,4,NORTH |
    | -2,0,NORTH |
    | -2,1,NORTH |
    | -2,2,NORTH |
    | -2,3,NORTH |
    | -2,4,NORTH |
    | -1,0,NORTH |
    | -1,1,NORTH |
    | -1,2,NORTH |
    | -1,3,NORTH |
    | -1,4,NORTH |
    | 5,0,NORTH |
    | 5,1,NORTH |
    | 5,2,NORTH |
    | 5,3,NORTH |
    | 5,4,NORTH |
    | 6,0,NORTH |
    | 6,1,NORTH |
    | 6,2,NORTH |
    | 6,3,NORTH |
    | 6,4,NORTH |
    | 7,0,NORTH |
    | 7,1,NORTH |
    | 7,2,NORTH |
    | 7,3,NORTH |
    | 7,4,NORTH |
    | 8,0,NORTH |
    | 8,1,NORTH |
    | 8,2,NORTH |
    | 8,3,NORTH |
    | 8,4,NORTH |
    | 9,0,NORTH |
    | 9,1,NORTH |
    | 9,2,NORTH |
    | 9,3,NORTH |
    | 9,4,NORTH |
  Examples: all invalid y-axis
    | position |
    | 0,-9,EAST |
    | 0,-8,EAST |
    | 0,-7,EAST |
    | 0,-6,EAST |
    | 0,-5,EAST |
    | 0,-4,EAST |
    | 0,-3,EAST |
    | 0,-2,EAST |
    | 0,-1,EAST |
    | 0,5,EAST |
    | 0,6,EAST |
    | 0,7,EAST |
    | 0,8,EAST |
    | 0,9,EAST |
    | 1,-9,EAST |
    | 1,-8,EAST |
    | 1,-7,EAST |
    | 1,-6,EAST |
    | 1,-5,EAST |
    | 1,-4,EAST |
    | 1,-3,EAST |
    | 1,-2,EAST |
    | 1,-1,EAST |
    | 1,5,EAST |
    | 1,6,EAST |
    | 1,7,EAST |
    | 1,8,EAST |
    | 1,9,EAST |
    | 2,-9,EAST |
    | 2,-8,EAST |
    | 2,-7,EAST |
    | 2,-6,EAST |
    | 2,-5,EAST |
    | 2,-4,EAST |
    | 2,-3,EAST |
    | 2,-2,EAST |
    | 2,-1,EAST |
    | 2,5,EAST |
    | 2,6,EAST |
    | 2,7,EAST |
    | 2,8,EAST |
    | 2,9,EAST |
    | 3,-9,EAST |
    | 3,-8,EAST |
    | 3,-7,EAST |
    | 3,-6,EAST |
    | 3,-5,EAST |
    | 3,-4,EAST |
    | 3,-3,EAST |
    | 3,-2,EAST |
    | 3,-1,EAST |
    | 3,5,EAST |
    | 3,6,EAST |
    | 3,7,EAST |
    | 3,8,EAST |
    | 3,9,EAST |
    | 4,-9,EAST |
    | 4,-8,EAST |
    | 4,-7,EAST |
    | 4,-6,EAST |
    | 4,-5,EAST |
    | 4,-4,EAST |
    | 4,-3,EAST |
    | 4,-2,EAST |
    | 4,-1,EAST |
    | 4,5,EAST |
    | 4,6,EAST |
    | 4,7,EAST |
    | 4,8,EAST |
    | 4,9,EAST |
    | 0,-9,SOUTH |
    | 0,-8,SOUTH |
    | 0,-7,SOUTH |
    | 0,-6,SOUTH |
    | 0,-5,SOUTH |
    | 0,-4,SOUTH |
    | 0,-3,SOUTH |
    | 0,-2,SOUTH |
    | 0,-1,SOUTH |
    | 0,5,SOUTH |
    | 0,6,SOUTH |
    | 0,7,SOUTH |
    | 0,8,SOUTH |
    | 0,9,SOUTH |
    | 1,-9,SOUTH |
    | 1,-8,SOUTH |
    | 1,-7,SOUTH |
    | 1,-6,SOUTH |
    | 1,-5,SOUTH |
    | 1,-4,SOUTH |
    | 1,-3,SOUTH |
    | 1,-2,SOUTH |
    | 1,-1,SOUTH |
    | 1,5,SOUTH |
    | 1,6,SOUTH |
    | 1,7,SOUTH |
    | 1,8,SOUTH |
    | 1,9,SOUTH |
    | 2,-9,SOUTH |
    | 2,-8,SOUTH |
    | 2,-7,SOUTH |
    | 2,-6,SOUTH |
    | 2,-5,SOUTH |
    | 2,-4,SOUTH |
    | 2,-3,SOUTH |
    | 2,-2,SOUTH |
    | 2,-1,SOUTH |
    | 2,5,SOUTH |
    | 2,6,SOUTH |
    | 2,7,SOUTH |
    | 2,8,SOUTH |
    | 2,9,SOUTH |
    | 3,-9,SOUTH |
    | 3,-8,SOUTH |
    | 3,-7,SOUTH |
    | 3,-6,SOUTH |
    | 3,-5,SOUTH |
    | 3,-4,SOUTH |
    | 3,-3,SOUTH |
    | 3,-2,SOUTH |
    | 3,-1,SOUTH |
    | 3,5,SOUTH |
    | 3,6,SOUTH |
    | 3,7,SOUTH |
    | 3,8,SOUTH |
    | 3,9,SOUTH |
    | 4,-9,SOUTH |
    | 4,-8,SOUTH |
    | 4,-7,SOUTH |
    | 4,-6,SOUTH |
    | 4,-5,SOUTH |
    | 4,-4,SOUTH |
    | 4,-3,SOUTH |
    | 4,-2,SOUTH |
    | 4,-1,SOUTH |
    | 4,5,SOUTH |
    | 4,6,SOUTH |
    | 4,7,SOUTH |
    | 4,8,SOUTH |
    | 4,9,SOUTH |
    | 0,-9,WEST |
    | 0,-8,WEST |
    | 0,-7,WEST |
    | 0,-6,WEST |
    | 0,-5,WEST |
    | 0,-4,WEST |
    | 0,-3,WEST |
    | 0,-2,WEST |
    | 0,-1,WEST |
    | 0,5,WEST |
    | 0,6,WEST |
    | 0,7,WEST |
    | 0,8,WEST |
    | 0,9,WEST |
    | 1,-9,WEST |
    | 1,-8,WEST |
    | 1,-7,WEST |
    | 1,-6,WEST |
    | 1,-5,WEST |
    | 1,-4,WEST |
    | 1,-3,WEST |
    | 1,-2,WEST |
    | 1,-1,WEST |
    | 1,5,WEST |
    | 1,6,WEST |
    | 1,7,WEST |
    | 1,8,WEST |
    | 1,9,WEST |
    | 2,-9,WEST |
    | 2,-8,WEST |
    | 2,-7,WEST |
    | 2,-6,WEST |
    | 2,-5,WEST |
    | 2,-4,WEST |
    | 2,-3,WEST |
    | 2,-2,WEST |
    | 2,-1,WEST |
    | 2,5,WEST |
    | 2,6,WEST |
    | 2,7,WEST |
    | 2,8,WEST |
    | 2,9,WEST |
    | 3,-9,WEST |
    | 3,-8,WEST |
    | 3,-7,WEST |
    | 3,-6,WEST |
    | 3,-5,WEST |
    | 3,-4,WEST |
    | 3,-3,WEST |
    | 3,-2,WEST |
    | 3,-1,WEST |
    | 3,5,WEST |
    | 3,6,WEST |
    | 3,7,WEST |
    | 3,8,WEST |
    | 3,9,WEST |
    | 4,-9,WEST |
    | 4,-8,WEST |
    | 4,-7,WEST |
    | 4,-6,WEST |
    | 4,-5,WEST |
    | 4,-4,WEST |
    | 4,-3,WEST |
    | 4,-2,WEST |
    | 4,-1,WEST |
    | 4,5,WEST |
    | 4,6,WEST |
    | 4,7,WEST |
    | 4,8,WEST |
    | 4,9,WEST |
    | 0,-9,NORTH |
    | 0,-8,NORTH |
    | 0,-7,NORTH |
    | 0,-6,NORTH |
    | 0,-5,NORTH |
    | 0,-4,NORTH |
    | 0,-3,NORTH |
    | 0,-2,NORTH |
    | 0,-1,NORTH |
    | 0,5,NORTH |
    | 0,6,NORTH |
    | 0,7,NORTH |
    | 0,8,NORTH |
    | 0,9,NORTH |
    | 1,-9,NORTH |
    | 1,-8,NORTH |
    | 1,-7,NORTH |
    | 1,-6,NORTH |
    | 1,-5,NORTH |
    | 1,-4,NORTH |
    | 1,-3,NORTH |
    | 1,-2,NORTH |
    | 1,-1,NORTH |
    | 1,5,NORTH |
    | 1,6,NORTH |
    | 1,7,NORTH |
    | 1,8,NORTH |
    | 1,9,NORTH |
    | 2,-9,NORTH |
    | 2,-8,NORTH |
    | 2,-7,NORTH |
    | 2,-6,NORTH |
    | 2,-5,NORTH |
    | 2,-4,NORTH |
    | 2,-3,NORTH |
    | 2,-2,NORTH |
    | 2,-1,NORTH |
    | 2,5,NORTH |
    | 2,6,NORTH |
    | 2,7,NORTH |
    | 2,8,NORTH |
    | 2,9,NORTH |
    | 3,-9,NORTH |
    | 3,-8,NORTH |
    | 3,-7,NORTH |
    | 3,-6,NORTH |
    | 3,-5,NORTH |
    | 3,-4,NORTH |
    | 3,-3,NORTH |
    | 3,-2,NORTH |
    | 3,-1,NORTH |
    | 3,5,NORTH |
    | 3,6,NORTH |
    | 3,7,NORTH |
    | 3,8,NORTH |
    | 3,9,NORTH |
    | 4,-9,NORTH |
    | 4,-8,NORTH |
    | 4,-7,NORTH |
    | 4,-6,NORTH |
    | 4,-5,NORTH |
    | 4,-4,NORTH |
    | 4,-3,NORTH |
    | 4,-2,NORTH |
    | 4,-1,NORTH |
    | 4,5,NORTH |
    | 4,6,NORTH |
    | 4,7,NORTH |
    | 4,8,NORTH |
    | 4,9,NORTH |
  Examples: all invalid xy-axis
    | position |
    | -9,-9,EAST |
    | -9,-8,EAST |
    | -9,-7,EAST |
    | -9,-6,EAST |
    | -9,-5,EAST |
    | -9,-4,EAST |
    | -9,-3,EAST |
    | -9,-2,EAST |
    | -9,-1,EAST |
    | -9,5,EAST |
    | -9,6,EAST |
    | -9,7,EAST |
    | -9,8,EAST |
    | -9,9,EAST |
    | -8,-9,EAST |
    | -8,-8,EAST |
    | -8,-7,EAST |
    | -8,-6,EAST |
    | -8,-5,EAST |
    | -8,-4,EAST |
    | -8,-3,EAST |
    | -8,-2,EAST |
    | -8,-1,EAST |
    | -8,5,EAST |
    | -8,6,EAST |
    | -8,7,EAST |
    | -8,8,EAST |
    | -8,9,EAST |
    | -7,-9,EAST |
    | -7,-8,EAST |
    | -7,-7,EAST |
    | -7,-6,EAST |
    | -7,-5,EAST |
    | -7,-4,EAST |
    | -7,-3,EAST |
    | -7,-2,EAST |
    | -7,-1,EAST |
    | -7,5,EAST |
    | -7,6,EAST |
    | -7,7,EAST |
    | -7,8,EAST |
    | -7,9,EAST |
    | -6,-9,EAST |
    | -6,-8,EAST |
    | -6,-7,EAST |
    | -6,-6,EAST |
    | -6,-5,EAST |
    | -6,-4,EAST |
    | -6,-3,EAST |
    | -6,-2,EAST |
    | -6,-1,EAST |
    | -6,5,EAST |
    | -6,6,EAST |
    | -6,7,EAST |
    | -6,8,EAST |
    | -6,9,EAST |
    | -5,-9,EAST |
    | -5,-8,EAST |
    | -5,-7,EAST |
    | -5,-6,EAST |
    | -5,-5,EAST |
    | -5,-4,EAST |
    | -5,-3,EAST |
    | -5,-2,EAST |
    | -5,-1,EAST |
    | -5,5,EAST |
    | -5,6,EAST |
    | -5,7,EAST |
    | -5,8,EAST |
    | -5,9,EAST |
    | -4,-9,EAST |
    | -4,-8,EAST |
    | -4,-7,EAST |
    | -4,-6,EAST |
    | -4,-5,EAST |
    | -4,-4,EAST |
    | -4,-3,EAST |
    | -4,-2,EAST |
    | -4,-1,EAST |
    | -4,5,EAST |
    | -4,6,EAST |
    | -4,7,EAST |
    | -4,8,EAST |
    | -4,9,EAST |
    | -3,-9,EAST |
    | -3,-8,EAST |
    | -3,-7,EAST |
    | -3,-6,EAST |
    | -3,-5,EAST |
    | -3,-4,EAST |
    | -3,-3,EAST |
    | -3,-2,EAST |
    | -3,-1,EAST |
    | -3,5,EAST |
    | -3,6,EAST |
    | -3,7,EAST |
    | -3,8,EAST |
    | -3,9,EAST |
    | -2,-9,EAST |
    | -2,-8,EAST |
    | -2,-7,EAST |
    | -2,-6,EAST |
    | -2,-5,EAST |
    | -2,-4,EAST |
    | -2,-3,EAST |
    | -2,-2,EAST |
    | -2,-1,EAST |
    | -2,5,EAST |
    | -2,6,EAST |
    | -2,7,EAST |
    | -2,8,EAST |
    | -2,9,EAST |
    | -1,-9,EAST |
    | -1,-8,EAST |
    | -1,-7,EAST |
    | -1,-6,EAST |
    | -1,-5,EAST |
    | -1,-4,EAST |
    | -1,-3,EAST |
    | -1,-2,EAST |
    | -1,-1,EAST |
    | -1,5,EAST |
    | -1,6,EAST |
    | -1,7,EAST |
    | -1,8,EAST |
    | -1,9,EAST |
    | 5,-9,EAST |
    | 5,-8,EAST |
    | 5,-7,EAST |
    | 5,-6,EAST |
    | 5,-5,EAST |
    | 5,-4,EAST |
    | 5,-3,EAST |
    | 5,-2,EAST |
    | 5,-1,EAST |
    | 5,5,EAST |
    | 5,6,EAST |
    | 5,7,EAST |
    | 5,8,EAST |
    | 5,9,EAST |
    | 6,-9,EAST |
    | 6,-8,EAST |
    | 6,-7,EAST |
    | 6,-6,EAST |
    | 6,-5,EAST |
    | 6,-4,EAST |
    | 6,-3,EAST |
    | 6,-2,EAST |
    | 6,-1,EAST |
    | 6,5,EAST |
    | 6,6,EAST |
    | 6,7,EAST |
    | 6,8,EAST |
    | 6,9,EAST |
    | 7,-9,EAST |
    | 7,-8,EAST |
    | 7,-7,EAST |
    | 7,-6,EAST |
    | 7,-5,EAST |
    | 7,-4,EAST |
    | 7,-3,EAST |
    | 7,-2,EAST |
    | 7,-1,EAST |
    | 7,5,EAST |
    | 7,6,EAST |
    | 7,7,EAST |
    | 7,8,EAST |
    | 7,9,EAST |
    | 8,-9,EAST |
    | 8,-8,EAST |
    | 8,-7,EAST |
    | 8,-6,EAST |
    | 8,-5,EAST |
    | 8,-4,EAST |
    | 8,-3,EAST |
    | 8,-2,EAST |
    | 8,-1,EAST |
    | 8,5,EAST |
    | 8,6,EAST |
    | 8,7,EAST |
    | 8,8,EAST |
    | 8,9,EAST |
    | 9,-9,EAST |
    | 9,-8,EAST |
    | 9,-7,EAST |
    | 9,-6,EAST |
    | 9,-5,EAST |
    | 9,-4,EAST |
    | 9,-3,EAST |
    | 9,-2,EAST |
    | 9,-1,EAST |
    | 9,5,EAST |
    | 9,6,EAST |
    | 9,7,EAST |
    | 9,8,EAST |
    | 9,9,EAST |
    | -9,-9,SOUTH |
    | -9,-8,SOUTH |
    | -9,-7,SOUTH |
    | -9,-6,SOUTH |
    | -9,-5,SOUTH |
    | -9,-4,SOUTH |
    | -9,-3,SOUTH |
    | -9,-2,SOUTH |
    | -9,-1,SOUTH |
    | -9,5,SOUTH |
    | -9,6,SOUTH |
    | -9,7,SOUTH |
    | -9,8,SOUTH |
    | -9,9,SOUTH |
    | -8,-9,SOUTH |
    | -8,-8,SOUTH |
    | -8,-7,SOUTH |
    | -8,-6,SOUTH |
    | -8,-5,SOUTH |
    | -8,-4,SOUTH |
    | -8,-3,SOUTH |
    | -8,-2,SOUTH |
    | -8,-1,SOUTH |
    | -8,5,SOUTH |
    | -8,6,SOUTH |
    | -8,7,SOUTH |
    | -8,8,SOUTH |
    | -8,9,SOUTH |
    | -7,-9,SOUTH |
    | -7,-8,SOUTH |
    | -7,-7,SOUTH |
    | -7,-6,SOUTH |
    | -7,-5,SOUTH |
    | -7,-4,SOUTH |
    | -7,-3,SOUTH |
    | -7,-2,SOUTH |
    | -7,-1,SOUTH |
    | -7,5,SOUTH |
    | -7,6,SOUTH |
    | -7,7,SOUTH |
    | -7,8,SOUTH |
    | -7,9,SOUTH |
    | -6,-9,SOUTH |
    | -6,-8,SOUTH |
    | -6,-7,SOUTH |
    | -6,-6,SOUTH |
    | -6,-5,SOUTH |
    | -6,-4,SOUTH |
    | -6,-3,SOUTH |
    | -6,-2,SOUTH |
    | -6,-1,SOUTH |
    | -6,5,SOUTH |
    | -6,6,SOUTH |
    | -6,7,SOUTH |
    | -6,8,SOUTH |
    | -6,9,SOUTH |
    | -5,-9,SOUTH |
    | -5,-8,SOUTH |
    | -5,-7,SOUTH |
    | -5,-6,SOUTH |
    | -5,-5,SOUTH |
    | -5,-4,SOUTH |
    | -5,-3,SOUTH |
    | -5,-2,SOUTH |
    | -5,-1,SOUTH |
    | -5,5,SOUTH |
    | -5,6,SOUTH |
    | -5,7,SOUTH |
    | -5,8,SOUTH |
    | -5,9,SOUTH |
    | -4,-9,SOUTH |
    | -4,-8,SOUTH |
    | -4,-7,SOUTH |
    | -4,-6,SOUTH |
    | -4,-5,SOUTH |
    | -4,-4,SOUTH |
    | -4,-3,SOUTH |
    | -4,-2,SOUTH |
    | -4,-1,SOUTH |
    | -4,5,SOUTH |
    | -4,6,SOUTH |
    | -4,7,SOUTH |
    | -4,8,SOUTH |
    | -4,9,SOUTH |
    | -3,-9,SOUTH |
    | -3,-8,SOUTH |
    | -3,-7,SOUTH |
    | -3,-6,SOUTH |
    | -3,-5,SOUTH |
    | -3,-4,SOUTH |
    | -3,-3,SOUTH |
    | -3,-2,SOUTH |
    | -3,-1,SOUTH |
    | -3,5,SOUTH |
    | -3,6,SOUTH |
    | -3,7,SOUTH |
    | -3,8,SOUTH |
    | -3,9,SOUTH |
    | -2,-9,SOUTH |
    | -2,-8,SOUTH |
    | -2,-7,SOUTH |
    | -2,-6,SOUTH |
    | -2,-5,SOUTH |
    | -2,-4,SOUTH |
    | -2,-3,SOUTH |
    | -2,-2,SOUTH |
    | -2,-1,SOUTH |
    | -2,5,SOUTH |
    | -2,6,SOUTH |
    | -2,7,SOUTH |
    | -2,8,SOUTH |
    | -2,9,SOUTH |
    | -1,-9,SOUTH |
    | -1,-8,SOUTH |
    | -1,-7,SOUTH |
    | -1,-6,SOUTH |
    | -1,-5,SOUTH |
    | -1,-4,SOUTH |
    | -1,-3,SOUTH |
    | -1,-2,SOUTH |
    | -1,-1,SOUTH |
    | -1,5,SOUTH |
    | -1,6,SOUTH |
    | -1,7,SOUTH |
    | -1,8,SOUTH |
    | -1,9,SOUTH |
    | 5,-9,SOUTH |
    | 5,-8,SOUTH |
    | 5,-7,SOUTH |
    | 5,-6,SOUTH |
    | 5,-5,SOUTH |
    | 5,-4,SOUTH |
    | 5,-3,SOUTH |
    | 5,-2,SOUTH |
    | 5,-1,SOUTH |
    | 5,5,SOUTH |
    | 5,6,SOUTH |
    | 5,7,SOUTH |
    | 5,8,SOUTH |
    | 5,9,SOUTH |
    | 6,-9,SOUTH |
    | 6,-8,SOUTH |
    | 6,-7,SOUTH |
    | 6,-6,SOUTH |
    | 6,-5,SOUTH |
    | 6,-4,SOUTH |
    | 6,-3,SOUTH |
    | 6,-2,SOUTH |
    | 6,-1,SOUTH |
    | 6,5,SOUTH |
    | 6,6,SOUTH |
    | 6,7,SOUTH |
    | 6,8,SOUTH |
    | 6,9,SOUTH |
    | 7,-9,SOUTH |
    | 7,-8,SOUTH |
    | 7,-7,SOUTH |
    | 7,-6,SOUTH |
    | 7,-5,SOUTH |
    | 7,-4,SOUTH |
    | 7,-3,SOUTH |
    | 7,-2,SOUTH |
    | 7,-1,SOUTH |
    | 7,5,SOUTH |
    | 7,6,SOUTH |
    | 7,7,SOUTH |
    | 7,8,SOUTH |
    | 7,9,SOUTH |
    | 8,-9,SOUTH |
    | 8,-8,SOUTH |
    | 8,-7,SOUTH |
    | 8,-6,SOUTH |
    | 8,-5,SOUTH |
    | 8,-4,SOUTH |
    | 8,-3,SOUTH |
    | 8,-2,SOUTH |
    | 8,-1,SOUTH |
    | 8,5,SOUTH |
    | 8,6,SOUTH |
    | 8,7,SOUTH |
    | 8,8,SOUTH |
    | 8,9,SOUTH |
    | 9,-9,SOUTH |
    | 9,-8,SOUTH |
    | 9,-7,SOUTH |
    | 9,-6,SOUTH |
    | 9,-5,SOUTH |
    | 9,-4,SOUTH |
    | 9,-3,SOUTH |
    | 9,-2,SOUTH |
    | 9,-1,SOUTH |
    | 9,5,SOUTH |
    | 9,6,SOUTH |
    | 9,7,SOUTH |
    | 9,8,SOUTH |
    | 9,9,SOUTH |
    | -9,-9,WEST |
    | -9,-8,WEST |
    | -9,-7,WEST |
    | -9,-6,WEST |
    | -9,-5,WEST |
    | -9,-4,WEST |
    | -9,-3,WEST |
    | -9,-2,WEST |
    | -9,-1,WEST |
    | -9,5,WEST |
    | -9,6,WEST |
    | -9,7,WEST |
    | -9,8,WEST |
    | -9,9,WEST |
    | -8,-9,WEST |
    | -8,-8,WEST |
    | -8,-7,WEST |
    | -8,-6,WEST |
    | -8,-5,WEST |
    | -8,-4,WEST |
    | -8,-3,WEST |
    | -8,-2,WEST |
    | -8,-1,WEST |
    | -8,5,WEST |
    | -8,6,WEST |
    | -8,7,WEST |
    | -8,8,WEST |
    | -8,9,WEST |
    | -7,-9,WEST |
    | -7,-8,WEST |
    | -7,-7,WEST |
    | -7,-6,WEST |
    | -7,-5,WEST |
    | -7,-4,WEST |
    | -7,-3,WEST |
    | -7,-2,WEST |
    | -7,-1,WEST |
    | -7,5,WEST |
    | -7,6,WEST |
    | -7,7,WEST |
    | -7,8,WEST |
    | -7,9,WEST |
    | -6,-9,WEST |
    | -6,-8,WEST |
    | -6,-7,WEST |
    | -6,-6,WEST |
    | -6,-5,WEST |
    | -6,-4,WEST |
    | -6,-3,WEST |
    | -6,-2,WEST |
    | -6,-1,WEST |
    | -6,5,WEST |
    | -6,6,WEST |
    | -6,7,WEST |
    | -6,8,WEST |
    | -6,9,WEST |
    | -5,-9,WEST |
    | -5,-8,WEST |
    | -5,-7,WEST |
    | -5,-6,WEST |
    | -5,-5,WEST |
    | -5,-4,WEST |
    | -5,-3,WEST |
    | -5,-2,WEST |
    | -5,-1,WEST |
    | -5,5,WEST |
    | -5,6,WEST |
    | -5,7,WEST |
    | -5,8,WEST |
    | -5,9,WEST |
    | -4,-9,WEST |
    | -4,-8,WEST |
    | -4,-7,WEST |
    | -4,-6,WEST |
    | -4,-5,WEST |
    | -4,-4,WEST |
    | -4,-3,WEST |
    | -4,-2,WEST |
    | -4,-1,WEST |
    | -4,5,WEST |
    | -4,6,WEST |
    | -4,7,WEST |
    | -4,8,WEST |
    | -4,9,WEST |
    | -3,-9,WEST |
    | -3,-8,WEST |
    | -3,-7,WEST |
    | -3,-6,WEST |
    | -3,-5,WEST |
    | -3,-4,WEST |
    | -3,-3,WEST |
    | -3,-2,WEST |
    | -3,-1,WEST |
    | -3,5,WEST |
    | -3,6,WEST |
    | -3,7,WEST |
    | -3,8,WEST |
    | -3,9,WEST |
    | -2,-9,WEST |
    | -2,-8,WEST |
    | -2,-7,WEST |
    | -2,-6,WEST |
    | -2,-5,WEST |
    | -2,-4,WEST |
    | -2,-3,WEST |
    | -2,-2,WEST |
    | -2,-1,WEST |
    | -2,5,WEST |
    | -2,6,WEST |
    | -2,7,WEST |
    | -2,8,WEST |
    | -2,9,WEST |
    | -1,-9,WEST |
    | -1,-8,WEST |
    | -1,-7,WEST |
    | -1,-6,WEST |
    | -1,-5,WEST |
    | -1,-4,WEST |
    | -1,-3,WEST |
    | -1,-2,WEST |
    | -1,-1,WEST |
    | -1,5,WEST |
    | -1,6,WEST |
    | -1,7,WEST |
    | -1,8,WEST |
    | -1,9,WEST |
    | 5,-9,WEST |
    | 5,-8,WEST |
    | 5,-7,WEST |
    | 5,-6,WEST |
    | 5,-5,WEST |
    | 5,-4,WEST |
    | 5,-3,WEST |
    | 5,-2,WEST |
    | 5,-1,WEST |
    | 5,5,WEST |
    | 5,6,WEST |
    | 5,7,WEST |
    | 5,8,WEST |
    | 5,9,WEST |
    | 6,-9,WEST |
    | 6,-8,WEST |
    | 6,-7,WEST |
    | 6,-6,WEST |
    | 6,-5,WEST |
    | 6,-4,WEST |
    | 6,-3,WEST |
    | 6,-2,WEST |
    | 6,-1,WEST |
    | 6,5,WEST |
    | 6,6,WEST |
    | 6,7,WEST |
    | 6,8,WEST |
    | 6,9,WEST |
    | 7,-9,WEST |
    | 7,-8,WEST |
    | 7,-7,WEST |
    | 7,-6,WEST |
    | 7,-5,WEST |
    | 7,-4,WEST |
    | 7,-3,WEST |
    | 7,-2,WEST |
    | 7,-1,WEST |
    | 7,5,WEST |
    | 7,6,WEST |
    | 7,7,WEST |
    | 7,8,WEST |
    | 7,9,WEST |
    | 8,-9,WEST |
    | 8,-8,WEST |
    | 8,-7,WEST |
    | 8,-6,WEST |
    | 8,-5,WEST |
    | 8,-4,WEST |
    | 8,-3,WEST |
    | 8,-2,WEST |
    | 8,-1,WEST |
    | 8,5,WEST |
    | 8,6,WEST |
    | 8,7,WEST |
    | 8,8,WEST |
    | 8,9,WEST |
    | 9,-9,WEST |
    | 9,-8,WEST |
    | 9,-7,WEST |
    | 9,-6,WEST |
    | 9,-5,WEST |
    | 9,-4,WEST |
    | 9,-3,WEST |
    | 9,-2,WEST |
    | 9,-1,WEST |
    | 9,5,WEST |
    | 9,6,WEST |
    | 9,7,WEST |
    | 9,8,WEST |
    | 9,9,WEST |
    | -9,-9,NORTH |
    | -9,-8,NORTH |
    | -9,-7,NORTH |
    | -9,-6,NORTH |
    | -9,-5,NORTH |
    | -9,-4,NORTH |
    | -9,-3,NORTH |
    | -9,-2,NORTH |
    | -9,-1,NORTH |
    | -9,5,NORTH |
    | -9,6,NORTH |
    | -9,7,NORTH |
    | -9,8,NORTH |
    | -9,9,NORTH |
    | -8,-9,NORTH |
    | -8,-8,NORTH |
    | -8,-7,NORTH |
    | -8,-6,NORTH |
    | -8,-5,NORTH |
    | -8,-4,NORTH |
    | -8,-3,NORTH |
    | -8,-2,NORTH |
    | -8,-1,NORTH |
    | -8,5,NORTH |
    | -8,6,NORTH |
    | -8,7,NORTH |
    | -8,8,NORTH |
    | -8,9,NORTH |
    | -7,-9,NORTH |
    | -7,-8,NORTH |
    | -7,-7,NORTH |
    | -7,-6,NORTH |
    | -7,-5,NORTH |
    | -7,-4,NORTH |
    | -7,-3,NORTH |
    | -7,-2,NORTH |
    | -7,-1,NORTH |
    | -7,5,NORTH |
    | -7,6,NORTH |
    | -7,7,NORTH |
    | -7,8,NORTH |
    | -7,9,NORTH |
    | -6,-9,NORTH |
    | -6,-8,NORTH |
    | -6,-7,NORTH |
    | -6,-6,NORTH |
    | -6,-5,NORTH |
    | -6,-4,NORTH |
    | -6,-3,NORTH |
    | -6,-2,NORTH |
    | -6,-1,NORTH |
    | -6,5,NORTH |
    | -6,6,NORTH |
    | -6,7,NORTH |
    | -6,8,NORTH |
    | -6,9,NORTH |
    | -5,-9,NORTH |
    | -5,-8,NORTH |
    | -5,-7,NORTH |
    | -5,-6,NORTH |
    | -5,-5,NORTH |
    | -5,-4,NORTH |
    | -5,-3,NORTH |
    | -5,-2,NORTH |
    | -5,-1,NORTH |
    | -5,5,NORTH |
    | -5,6,NORTH |
    | -5,7,NORTH |
    | -5,8,NORTH |
    | -5,9,NORTH |
    | -4,-9,NORTH |
    | -4,-8,NORTH |
    | -4,-7,NORTH |
    | -4,-6,NORTH |
    | -4,-5,NORTH |
    | -4,-4,NORTH |
    | -4,-3,NORTH |
    | -4,-2,NORTH |
    | -4,-1,NORTH |
    | -4,5,NORTH |
    | -4,6,NORTH |
    | -4,7,NORTH |
    | -4,8,NORTH |
    | -4,9,NORTH |
    | -3,-9,NORTH |
    | -3,-8,NORTH |
    | -3,-7,NORTH |
    | -3,-6,NORTH |
    | -3,-5,NORTH |
    | -3,-4,NORTH |
    | -3,-3,NORTH |
    | -3,-2,NORTH |
    | -3,-1,NORTH |
    | -3,5,NORTH |
    | -3,6,NORTH |
    | -3,7,NORTH |
    | -3,8,NORTH |
    | -3,9,NORTH |
    | -2,-9,NORTH |
    | -2,-8,NORTH |
    | -2,-7,NORTH |
    | -2,-6,NORTH |
    | -2,-5,NORTH |
    | -2,-4,NORTH |
    | -2,-3,NORTH |
    | -2,-2,NORTH |
    | -2,-1,NORTH |
    | -2,5,NORTH |
    | -2,6,NORTH |
    | -2,7,NORTH |
    | -2,8,NORTH |
    | -2,9,NORTH |
    | -1,-9,NORTH |
    | -1,-8,NORTH |
    | -1,-7,NORTH |
    | -1,-6,NORTH |
    | -1,-5,NORTH |
    | -1,-4,NORTH |
    | -1,-3,NORTH |
    | -1,-2,NORTH |
    | -1,-1,NORTH |
    | -1,5,NORTH |
    | -1,6,NORTH |
    | -1,7,NORTH |
    | -1,8,NORTH |
    | -1,9,NORTH |
    | 5,-9,NORTH |
    | 5,-8,NORTH |
    | 5,-7,NORTH |
    | 5,-6,NORTH |
    | 5,-5,NORTH |
    | 5,-4,NORTH |
    | 5,-3,NORTH |
    | 5,-2,NORTH |
    | 5,-1,NORTH |
    | 5,5,NORTH |
    | 5,6,NORTH |
    | 5,7,NORTH |
    | 5,8,NORTH |
    | 5,9,NORTH |
    | 6,-9,NORTH |
    | 6,-8,NORTH |
    | 6,-7,NORTH |
    | 6,-6,NORTH |
    | 6,-5,NORTH |
    | 6,-4,NORTH |
    | 6,-3,NORTH |
    | 6,-2,NORTH |
    | 6,-1,NORTH |
    | 6,5,NORTH |
    | 6,6,NORTH |
    | 6,7,NORTH |
    | 6,8,NORTH |
    | 6,9,NORTH |
    | 7,-9,NORTH |
    | 7,-8,NORTH |
    | 7,-7,NORTH |
    | 7,-6,NORTH |
    | 7,-5,NORTH |
    | 7,-4,NORTH |
    | 7,-3,NORTH |
    | 7,-2,NORTH |
    | 7,-1,NORTH |
    | 7,5,NORTH |
    | 7,6,NORTH |
    | 7,7,NORTH |
    | 7,8,NORTH |
    | 7,9,NORTH |
    | 8,-9,NORTH |
    | 8,-8,NORTH |
    | 8,-7,NORTH |
    | 8,-6,NORTH |
    | 8,-5,NORTH |
    | 8,-4,NORTH |
    | 8,-3,NORTH |
    | 8,-2,NORTH |
    | 8,-1,NORTH |
    | 8,5,NORTH |
    | 8,6,NORTH |
    | 8,7,NORTH |
    | 8,8,NORTH |
    | 8,9,NORTH |
    | 9,-9,NORTH |
    | 9,-8,NORTH |
    | 9,-7,NORTH |
    | 9,-6,NORTH |
    | 9,-5,NORTH |
    | 9,-4,NORTH |
    | 9,-3,NORTH |
    | 9,-2,NORTH |
    | 9,-1,NORTH |
    | 9,5,NORTH |
    | 9,6,NORTH |
    | 9,7,NORTH |
    | 9,8,NORTH |
    | 9,9,NORTH |
  Examples: all invalid facing
    | position |
    | 0,0,UP |
    | 0,1,UP |
    | 0,2,UP |
    | 0,3,UP |
    | 0,4,UP |
    | 1,0,UP |
    | 1,1,UP |
    | 1,2,UP |
    | 1,3,UP |
    | 1,4,UP |
    | 2,0,UP |
    | 2,1,UP |
    | 2,2,UP |
    | 2,3,UP |
    | 2,4,UP |
    | 3,0,UP |
    | 3,1,UP |
    | 3,2,UP |
    | 3,3,UP |
    | 3,4,UP |
    | 4,0,UP |
    | 4,1,UP |
    | 4,2,UP |
    | 4,3,UP |
    | 4,4,UP |
    | 0,0,NORTH-WEST |
    | 0,1,NORTH-WEST |
    | 0,2,NORTH-WEST |
    | 0,3,NORTH-WEST |
    | 0,4,NORTH-WEST |
    | 1,0,NORTH-WEST |
    | 1,1,NORTH-WEST |
    | 1,2,NORTH-WEST |
    | 1,3,NORTH-WEST |
    | 1,4,NORTH-WEST |
    | 2,0,NORTH-WEST |
    | 2,1,NORTH-WEST |
    | 2,2,NORTH-WEST |
    | 2,3,NORTH-WEST |
    | 2,4,NORTH-WEST |
    | 3,0,NORTH-WEST |
    | 3,1,NORTH-WEST |
    | 3,2,NORTH-WEST |
    | 3,3,NORTH-WEST |
    | 3,4,NORTH-WEST |
    | 4,0,NORTH-WEST |
    | 4,1,NORTH-WEST |
    | 4,2,NORTH-WEST |
    | 4,3,NORTH-WEST |
    | 4,4,NORTH-WEST |
    | 0,0,NORTH-EAST |
    | 0,1,NORTH-EAST |
    | 0,2,NORTH-EAST |
    | 0,3,NORTH-EAST |
    | 0,4,NORTH-EAST |
    | 1,0,NORTH-EAST |
    | 1,1,NORTH-EAST |
    | 1,2,NORTH-EAST |
    | 1,3,NORTH-EAST |
    | 1,4,NORTH-EAST |
    | 2,0,NORTH-EAST |
    | 2,1,NORTH-EAST |
    | 2,2,NORTH-EAST |
    | 2,3,NORTH-EAST |
    | 2,4,NORTH-EAST |
    | 3,0,NORTH-EAST |
    | 3,1,NORTH-EAST |
    | 3,2,NORTH-EAST |
    | 3,3,NORTH-EAST |
    | 3,4,NORTH-EAST |
    | 4,0,NORTH-EAST |
    | 4,1,NORTH-EAST |
    | 4,2,NORTH-EAST |
    | 4,3,NORTH-EAST |
    | 4,4,NORTH-EAST |
    | 0,0,DOWN |
    | 0,1,DOWN |
    | 0,2,DOWN |
    | 0,3,DOWN |
    | 0,4,DOWN |
    | 1,0,DOWN |
    | 1,1,DOWN |
    | 1,2,DOWN |
    | 1,3,DOWN |
    | 1,4,DOWN |
    | 2,0,DOWN |
    | 2,1,DOWN |
    | 2,2,DOWN |
    | 2,3,DOWN |
    | 2,4,DOWN |
    | 3,0,DOWN |
    | 3,1,DOWN |
    | 3,2,DOWN |
    | 3,3,DOWN |
    | 3,4,DOWN |
    | 4,0,DOWN |
    | 4,1,DOWN |
    | 4,2,DOWN |
    | 4,3,DOWN |
    | 4,4,DOWN |
  Examples: all invalid xyfacing
    | position |
    | -9,-9,UP |
    | -9,-8,UP |
    | -9,-7,UP |
    | -9,-6,UP |
    | -9,-5,UP |
    | -9,-4,UP |
    | -9,-3,UP |
    | -9,-2,UP |
    | -9,-1,UP |
    | -9,5,UP |
    | -9,6,UP |
    | -9,7,UP |
    | -9,8,UP |
    | -9,9,UP |
    | -8,-9,UP |
    | -8,-8,UP |
    | -8,-7,UP |
    | -8,-6,UP |
    | -8,-5,UP |
    | -8,-4,UP |
    | -8,-3,UP |
    | -8,-2,UP |
    | -8,-1,UP |
    | -8,5,UP |
    | -8,6,UP |
    | -8,7,UP |
    | -8,8,UP |
    | -8,9,UP |
    | -7,-9,UP |
    | -7,-8,UP |
    | -7,-7,UP |
    | -7,-6,UP |
    | -7,-5,UP |
    | -7,-4,UP |
    | -7,-3,UP |
    | -7,-2,UP |
    | -7,-1,UP |
    | -7,5,UP |
    | -7,6,UP |
    | -7,7,UP |
    | -7,8,UP |
    | -7,9,UP |
    | -6,-9,UP |
    | -6,-8,UP |
    | -6,-7,UP |
    | -6,-6,UP |
    | -6,-5,UP |
    | -6,-4,UP |
    | -6,-3,UP |
    | -6,-2,UP |
    | -6,-1,UP |
    | -6,5,UP |
    | -6,6,UP |
    | -6,7,UP |
    | -6,8,UP |
    | -6,9,UP |
    | -5,-9,UP |
    | -5,-8,UP |
    | -5,-7,UP |
    | -5,-6,UP |
    | -5,-5,UP |
    | -5,-4,UP |
    | -5,-3,UP |
    | -5,-2,UP |
    | -5,-1,UP |
    | -5,5,UP |
    | -5,6,UP |
    | -5,7,UP |
    | -5,8,UP |
    | -5,9,UP |
    | -4,-9,UP |
    | -4,-8,UP |
    | -4,-7,UP |
    | -4,-6,UP |
    | -4,-5,UP |
    | -4,-4,UP |
    | -4,-3,UP |
    | -4,-2,UP |
    | -4,-1,UP |
    | -4,5,UP |
    | -4,6,UP |
    | -4,7,UP |
    | -4,8,UP |
    | -4,9,UP |
    | -3,-9,UP |
    | -3,-8,UP |
    | -3,-7,UP |
    | -3,-6,UP |
    | -3,-5,UP |
    | -3,-4,UP |
    | -3,-3,UP |
    | -3,-2,UP |
    | -3,-1,UP |
    | -3,5,UP |
    | -3,6,UP |
    | -3,7,UP |
    | -3,8,UP |
    | -3,9,UP |
    | -2,-9,UP |
    | -2,-8,UP |
    | -2,-7,UP |
    | -2,-6,UP |
    | -2,-5,UP |
    | -2,-4,UP |
    | -2,-3,UP |
    | -2,-2,UP |
    | -2,-1,UP |
    | -2,5,UP |
    | -2,6,UP |
    | -2,7,UP |
    | -2,8,UP |
    | -2,9,UP |
    | -1,-9,UP |
    | -1,-8,UP |
    | -1,-7,UP |
    | -1,-6,UP |
    | -1,-5,UP |
    | -1,-4,UP |
    | -1,-3,UP |
    | -1,-2,UP |
    | -1,-1,UP |
    | -1,5,UP |
    | -1,6,UP |
    | -1,7,UP |
    | -1,8,UP |
    | -1,9,UP |
    | 5,-9,UP |
    | 5,-8,UP |
    | 5,-7,UP |
    | 5,-6,UP |
    | 5,-5,UP |
    | 5,-4,UP |
    | 5,-3,UP |
    | 5,-2,UP |
    | 5,-1,UP |
    | 5,5,UP |
    | 5,6,UP |
    | 5,7,UP |
    | 5,8,UP |
    | 5,9,UP |
    | 6,-9,UP |
    | 6,-8,UP |
    | 6,-7,UP |
    | 6,-6,UP |
    | 6,-5,UP |
    | 6,-4,UP |
    | 6,-3,UP |
    | 6,-2,UP |
    | 6,-1,UP |
    | 6,5,UP |
    | 6,6,UP |
    | 6,7,UP |
    | 6,8,UP |
    | 6,9,UP |
    | 7,-9,UP |
    | 7,-8,UP |
    | 7,-7,UP |
    | 7,-6,UP |
    | 7,-5,UP |
    | 7,-4,UP |
    | 7,-3,UP |
    | 7,-2,UP |
    | 7,-1,UP |
    | 7,5,UP |
    | 7,6,UP |
    | 7,7,UP |
    | 7,8,UP |
    | 7,9,UP |
    | 8,-9,UP |
    | 8,-8,UP |
    | 8,-7,UP |
    | 8,-6,UP |
    | 8,-5,UP |
    | 8,-4,UP |
    | 8,-3,UP |
    | 8,-2,UP |
    | 8,-1,UP |
    | 8,5,UP |
    | 8,6,UP |
    | 8,7,UP |
    | 8,8,UP |
    | 8,9,UP |
    | 9,-9,UP |
    | 9,-8,UP |
    | 9,-7,UP |
    | 9,-6,UP |
    | 9,-5,UP |
    | 9,-4,UP |
    | 9,-3,UP |
    | 9,-2,UP |
    | 9,-1,UP |
    | 9,5,UP |
    | 9,6,UP |
    | 9,7,UP |
    | 9,8,UP |
    | 9,9,UP |
    | -9,-9,NORTH-WEST |
    | -9,-8,NORTH-WEST |
    | -9,-7,NORTH-WEST |
    | -9,-6,NORTH-WEST |
    | -9,-5,NORTH-WEST |
    | -9,-4,NORTH-WEST |
    | -9,-3,NORTH-WEST |
    | -9,-2,NORTH-WEST |
    | -9,-1,NORTH-WEST |
    | -9,5,NORTH-WEST |
    | -9,6,NORTH-WEST |
    | -9,7,NORTH-WEST |
    | -9,8,NORTH-WEST |
    | -9,9,NORTH-WEST |
    | -8,-9,NORTH-WEST |
    | -8,-8,NORTH-WEST |
    | -8,-7,NORTH-WEST |
    | -8,-6,NORTH-WEST |
    | -8,-5,NORTH-WEST |
    | -8,-4,NORTH-WEST |
    | -8,-3,NORTH-WEST |
    | -8,-2,NORTH-WEST |
    | -8,-1,NORTH-WEST |
    | -8,5,NORTH-WEST |
    | -8,6,NORTH-WEST |
    | -8,7,NORTH-WEST |
    | -8,8,NORTH-WEST |
    | -8,9,NORTH-WEST |
    | -7,-9,NORTH-WEST |
    | -7,-8,NORTH-WEST |
    | -7,-7,NORTH-WEST |
    | -7,-6,NORTH-WEST |
    | -7,-5,NORTH-WEST |
    | -7,-4,NORTH-WEST |
    | -7,-3,NORTH-WEST |
    | -7,-2,NORTH-WEST |
    | -7,-1,NORTH-WEST |
    | -7,5,NORTH-WEST |
    | -7,6,NORTH-WEST |
    | -7,7,NORTH-WEST |
    | -7,8,NORTH-WEST |
    | -7,9,NORTH-WEST |
    | -6,-9,NORTH-WEST |
    | -6,-8,NORTH-WEST |
    | -6,-7,NORTH-WEST |
    | -6,-6,NORTH-WEST |
    | -6,-5,NORTH-WEST |
    | -6,-4,NORTH-WEST |
    | -6,-3,NORTH-WEST |
    | -6,-2,NORTH-WEST |
    | -6,-1,NORTH-WEST |
    | -6,5,NORTH-WEST |
    | -6,6,NORTH-WEST |
    | -6,7,NORTH-WEST |
    | -6,8,NORTH-WEST |
    | -6,9,NORTH-WEST |
    | -5,-9,NORTH-WEST |
    | -5,-8,NORTH-WEST |
    | -5,-7,NORTH-WEST |
    | -5,-6,NORTH-WEST |
    | -5,-5,NORTH-WEST |
    | -5,-4,NORTH-WEST |
    | -5,-3,NORTH-WEST |
    | -5,-2,NORTH-WEST |
    | -5,-1,NORTH-WEST |
    | -5,5,NORTH-WEST |
    | -5,6,NORTH-WEST |
    | -5,7,NORTH-WEST |
    | -5,8,NORTH-WEST |
    | -5,9,NORTH-WEST |
    | -4,-9,NORTH-WEST |
    | -4,-8,NORTH-WEST |
    | -4,-7,NORTH-WEST |
    | -4,-6,NORTH-WEST |
    | -4,-5,NORTH-WEST |
    | -4,-4,NORTH-WEST |
    | -4,-3,NORTH-WEST |
    | -4,-2,NORTH-WEST |
    | -4,-1,NORTH-WEST |
    | -4,5,NORTH-WEST |
    | -4,6,NORTH-WEST |
    | -4,7,NORTH-WEST |
    | -4,8,NORTH-WEST |
    | -4,9,NORTH-WEST |
    | -3,-9,NORTH-WEST |
    | -3,-8,NORTH-WEST |
    | -3,-7,NORTH-WEST |
    | -3,-6,NORTH-WEST |
    | -3,-5,NORTH-WEST |
    | -3,-4,NORTH-WEST |
    | -3,-3,NORTH-WEST |
    | -3,-2,NORTH-WEST |
    | -3,-1,NORTH-WEST |
    | -3,5,NORTH-WEST |
    | -3,6,NORTH-WEST |
    | -3,7,NORTH-WEST |
    | -3,8,NORTH-WEST |
    | -3,9,NORTH-WEST |
    | -2,-9,NORTH-WEST |
    | -2,-8,NORTH-WEST |
    | -2,-7,NORTH-WEST |
    | -2,-6,NORTH-WEST |
    | -2,-5,NORTH-WEST |
    | -2,-4,NORTH-WEST |
    | -2,-3,NORTH-WEST |
    | -2,-2,NORTH-WEST |
    | -2,-1,NORTH-WEST |
    | -2,5,NORTH-WEST |
    | -2,6,NORTH-WEST |
    | -2,7,NORTH-WEST |
    | -2,8,NORTH-WEST |
    | -2,9,NORTH-WEST |
    | -1,-9,NORTH-WEST |
    | -1,-8,NORTH-WEST |
    | -1,-7,NORTH-WEST |
    | -1,-6,NORTH-WEST |
    | -1,-5,NORTH-WEST |
    | -1,-4,NORTH-WEST |
    | -1,-3,NORTH-WEST |
    | -1,-2,NORTH-WEST |
    | -1,-1,NORTH-WEST |
    | -1,5,NORTH-WEST |
    | -1,6,NORTH-WEST |
    | -1,7,NORTH-WEST |
    | -1,8,NORTH-WEST |
    | -1,9,NORTH-WEST |
    | 5,-9,NORTH-WEST |
    | 5,-8,NORTH-WEST |
    | 5,-7,NORTH-WEST |
    | 5,-6,NORTH-WEST |
    | 5,-5,NORTH-WEST |
    | 5,-4,NORTH-WEST |
    | 5,-3,NORTH-WEST |
    | 5,-2,NORTH-WEST |
    | 5,-1,NORTH-WEST |
    | 5,5,NORTH-WEST |
    | 5,6,NORTH-WEST |
    | 5,7,NORTH-WEST |
    | 5,8,NORTH-WEST |
    | 5,9,NORTH-WEST |
    | 6,-9,NORTH-WEST |
    | 6,-8,NORTH-WEST |
    | 6,-7,NORTH-WEST |
    | 6,-6,NORTH-WEST |
    | 6,-5,NORTH-WEST |
    | 6,-4,NORTH-WEST |
    | 6,-3,NORTH-WEST |
    | 6,-2,NORTH-WEST |
    | 6,-1,NORTH-WEST |
    | 6,5,NORTH-WEST |
    | 6,6,NORTH-WEST |
    | 6,7,NORTH-WEST |
    | 6,8,NORTH-WEST |
    | 6,9,NORTH-WEST |
    | 7,-9,NORTH-WEST |
    | 7,-8,NORTH-WEST |
    | 7,-7,NORTH-WEST |
    | 7,-6,NORTH-WEST |
    | 7,-5,NORTH-WEST |
    | 7,-4,NORTH-WEST |
    | 7,-3,NORTH-WEST |
    | 7,-2,NORTH-WEST |
    | 7,-1,NORTH-WEST |
    | 7,5,NORTH-WEST |
    | 7,6,NORTH-WEST |
    | 7,7,NORTH-WEST |
    | 7,8,NORTH-WEST |
    | 7,9,NORTH-WEST |
    | 8,-9,NORTH-WEST |
    | 8,-8,NORTH-WEST |
    | 8,-7,NORTH-WEST |
    | 8,-6,NORTH-WEST |
    | 8,-5,NORTH-WEST |
    | 8,-4,NORTH-WEST |
    | 8,-3,NORTH-WEST |
    | 8,-2,NORTH-WEST |
    | 8,-1,NORTH-WEST |
    | 8,5,NORTH-WEST |
    | 8,6,NORTH-WEST |
    | 8,7,NORTH-WEST |
    | 8,8,NORTH-WEST |
    | 8,9,NORTH-WEST |
    | 9,-9,NORTH-WEST |
    | 9,-8,NORTH-WEST |
    | 9,-7,NORTH-WEST |
    | 9,-6,NORTH-WEST |
    | 9,-5,NORTH-WEST |
    | 9,-4,NORTH-WEST |
    | 9,-3,NORTH-WEST |
    | 9,-2,NORTH-WEST |
    | 9,-1,NORTH-WEST |
    | 9,5,NORTH-WEST |
    | 9,6,NORTH-WEST |
    | 9,7,NORTH-WEST |
    | 9,8,NORTH-WEST |
    | 9,9,NORTH-WEST |
    | -9,-9,NORTH-EAST |
    | -9,-8,NORTH-EAST |
    | -9,-7,NORTH-EAST |
    | -9,-6,NORTH-EAST |
    | -9,-5,NORTH-EAST |
    | -9,-4,NORTH-EAST |
    | -9,-3,NORTH-EAST |
    | -9,-2,NORTH-EAST |
    | -9,-1,NORTH-EAST |
    | -9,5,NORTH-EAST |
    | -9,6,NORTH-EAST |
    | -9,7,NORTH-EAST |
    | -9,8,NORTH-EAST |
    | -9,9,NORTH-EAST |
    | -8,-9,NORTH-EAST |
    | -8,-8,NORTH-EAST |
    | -8,-7,NORTH-EAST |
    | -8,-6,NORTH-EAST |
    | -8,-5,NORTH-EAST |
    | -8,-4,NORTH-EAST |
    | -8,-3,NORTH-EAST |
    | -8,-2,NORTH-EAST |
    | -8,-1,NORTH-EAST |
    | -8,5,NORTH-EAST |
    | -8,6,NORTH-EAST |
    | -8,7,NORTH-EAST |
    | -8,8,NORTH-EAST |
    | -8,9,NORTH-EAST |
    | -7,-9,NORTH-EAST |
    | -7,-8,NORTH-EAST |
    | -7,-7,NORTH-EAST |
    | -7,-6,NORTH-EAST |
    | -7,-5,NORTH-EAST |
    | -7,-4,NORTH-EAST |
    | -7,-3,NORTH-EAST |
    | -7,-2,NORTH-EAST |
    | -7,-1,NORTH-EAST |
    | -7,5,NORTH-EAST |
    | -7,6,NORTH-EAST |
    | -7,7,NORTH-EAST |
    | -7,8,NORTH-EAST |
    | -7,9,NORTH-EAST |
    | -6,-9,NORTH-EAST |
    | -6,-8,NORTH-EAST |
    | -6,-7,NORTH-EAST |
    | -6,-6,NORTH-EAST |
    | -6,-5,NORTH-EAST |
    | -6,-4,NORTH-EAST |
    | -6,-3,NORTH-EAST |
    | -6,-2,NORTH-EAST |
    | -6,-1,NORTH-EAST |
    | -6,5,NORTH-EAST |
    | -6,6,NORTH-EAST |
    | -6,7,NORTH-EAST |
    | -6,8,NORTH-EAST |
    | -6,9,NORTH-EAST |
    | -5,-9,NORTH-EAST |
    | -5,-8,NORTH-EAST |
    | -5,-7,NORTH-EAST |
    | -5,-6,NORTH-EAST |
    | -5,-5,NORTH-EAST |
    | -5,-4,NORTH-EAST |
    | -5,-3,NORTH-EAST |
    | -5,-2,NORTH-EAST |
    | -5,-1,NORTH-EAST |
    | -5,5,NORTH-EAST |
    | -5,6,NORTH-EAST |
    | -5,7,NORTH-EAST |
    | -5,8,NORTH-EAST |
    | -5,9,NORTH-EAST |
    | -4,-9,NORTH-EAST |
    | -4,-8,NORTH-EAST |
    | -4,-7,NORTH-EAST |
    | -4,-6,NORTH-EAST |
    | -4,-5,NORTH-EAST |
    | -4,-4,NORTH-EAST |
    | -4,-3,NORTH-EAST |
    | -4,-2,NORTH-EAST |
    | -4,-1,NORTH-EAST |
    | -4,5,NORTH-EAST |
    | -4,6,NORTH-EAST |
    | -4,7,NORTH-EAST |
    | -4,8,NORTH-EAST |
    | -4,9,NORTH-EAST |
    | -3,-9,NORTH-EAST |
    | -3,-8,NORTH-EAST |
    | -3,-7,NORTH-EAST |
    | -3,-6,NORTH-EAST |
    | -3,-5,NORTH-EAST |
    | -3,-4,NORTH-EAST |
    | -3,-3,NORTH-EAST |
    | -3,-2,NORTH-EAST |
    | -3,-1,NORTH-EAST |
    | -3,5,NORTH-EAST |
    | -3,6,NORTH-EAST |
    | -3,7,NORTH-EAST |
    | -3,8,NORTH-EAST |
    | -3,9,NORTH-EAST |
    | -2,-9,NORTH-EAST |
    | -2,-8,NORTH-EAST |
    | -2,-7,NORTH-EAST |
    | -2,-6,NORTH-EAST |
    | -2,-5,NORTH-EAST |
    | -2,-4,NORTH-EAST |
    | -2,-3,NORTH-EAST |
    | -2,-2,NORTH-EAST |
    | -2,-1,NORTH-EAST |
    | -2,5,NORTH-EAST |
    | -2,6,NORTH-EAST |
    | -2,7,NORTH-EAST |
    | -2,8,NORTH-EAST |
    | -2,9,NORTH-EAST |
    | -1,-9,NORTH-EAST |
    | -1,-8,NORTH-EAST |
    | -1,-7,NORTH-EAST |
    | -1,-6,NORTH-EAST |
    | -1,-5,NORTH-EAST |
    | -1,-4,NORTH-EAST |
    | -1,-3,NORTH-EAST |
    | -1,-2,NORTH-EAST |
    | -1,-1,NORTH-EAST |
    | -1,5,NORTH-EAST |
    | -1,6,NORTH-EAST |
    | -1,7,NORTH-EAST |
    | -1,8,NORTH-EAST |
    | -1,9,NORTH-EAST |
    | 5,-9,NORTH-EAST |
    | 5,-8,NORTH-EAST |
    | 5,-7,NORTH-EAST |
    | 5,-6,NORTH-EAST |
    | 5,-5,NORTH-EAST |
    | 5,-4,NORTH-EAST |
    | 5,-3,NORTH-EAST |
    | 5,-2,NORTH-EAST |
    | 5,-1,NORTH-EAST |
    | 5,5,NORTH-EAST |
    | 5,6,NORTH-EAST |
    | 5,7,NORTH-EAST |
    | 5,8,NORTH-EAST |
    | 5,9,NORTH-EAST |
    | 6,-9,NORTH-EAST |
    | 6,-8,NORTH-EAST |
    | 6,-7,NORTH-EAST |
    | 6,-6,NORTH-EAST |
    | 6,-5,NORTH-EAST |
    | 6,-4,NORTH-EAST |
    | 6,-3,NORTH-EAST |
    | 6,-2,NORTH-EAST |
    | 6,-1,NORTH-EAST |
    | 6,5,NORTH-EAST |
    | 6,6,NORTH-EAST |
    | 6,7,NORTH-EAST |
    | 6,8,NORTH-EAST |
    | 6,9,NORTH-EAST |
    | 7,-9,NORTH-EAST |
    | 7,-8,NORTH-EAST |
    | 7,-7,NORTH-EAST |
    | 7,-6,NORTH-EAST |
    | 7,-5,NORTH-EAST |
    | 7,-4,NORTH-EAST |
    | 7,-3,NORTH-EAST |
    | 7,-2,NORTH-EAST |
    | 7,-1,NORTH-EAST |
    | 7,5,NORTH-EAST |
    | 7,6,NORTH-EAST |
    | 7,7,NORTH-EAST |
    | 7,8,NORTH-EAST |
    | 7,9,NORTH-EAST |
    | 8,-9,NORTH-EAST |
    | 8,-8,NORTH-EAST |
    | 8,-7,NORTH-EAST |
    | 8,-6,NORTH-EAST |
    | 8,-5,NORTH-EAST |
    | 8,-4,NORTH-EAST |
    | 8,-3,NORTH-EAST |
    | 8,-2,NORTH-EAST |
    | 8,-1,NORTH-EAST |
    | 8,5,NORTH-EAST |
    | 8,6,NORTH-EAST |
    | 8,7,NORTH-EAST |
    | 8,8,NORTH-EAST |
    | 8,9,NORTH-EAST |
    | 9,-9,NORTH-EAST |
    | 9,-8,NORTH-EAST |
    | 9,-7,NORTH-EAST |
    | 9,-6,NORTH-EAST |
    | 9,-5,NORTH-EAST |
    | 9,-4,NORTH-EAST |
    | 9,-3,NORTH-EAST |
    | 9,-2,NORTH-EAST |
    | 9,-1,NORTH-EAST |
    | 9,5,NORTH-EAST |
    | 9,6,NORTH-EAST |
    | 9,7,NORTH-EAST |
    | 9,8,NORTH-EAST |
    | 9,9,NORTH-EAST |
    | -9,-9,DOWN |
    | -9,-8,DOWN |
    | -9,-7,DOWN |
    | -9,-6,DOWN |
    | -9,-5,DOWN |
    | -9,-4,DOWN |
    | -9,-3,DOWN |
    | -9,-2,DOWN |
    | -9,-1,DOWN |
    | -9,5,DOWN |
    | -9,6,DOWN |
    | -9,7,DOWN |
    | -9,8,DOWN |
    | -9,9,DOWN |
    | -8,-9,DOWN |
    | -8,-8,DOWN |
    | -8,-7,DOWN |
    | -8,-6,DOWN |
    | -8,-5,DOWN |
    | -8,-4,DOWN |
    | -8,-3,DOWN |
    | -8,-2,DOWN |
    | -8,-1,DOWN |
    | -8,5,DOWN |
    | -8,6,DOWN |
    | -8,7,DOWN |
    | -8,8,DOWN |
    | -8,9,DOWN |
    | -7,-9,DOWN |
    | -7,-8,DOWN |
    | -7,-7,DOWN |
    | -7,-6,DOWN |
    | -7,-5,DOWN |
    | -7,-4,DOWN |
    | -7,-3,DOWN |
    | -7,-2,DOWN |
    | -7,-1,DOWN |
    | -7,5,DOWN |
    | -7,6,DOWN |
    | -7,7,DOWN |
    | -7,8,DOWN |
    | -7,9,DOWN |
    | -6,-9,DOWN |
    | -6,-8,DOWN |
    | -6,-7,DOWN |
    | -6,-6,DOWN |
    | -6,-5,DOWN |
    | -6,-4,DOWN |
    | -6,-3,DOWN |
    | -6,-2,DOWN |
    | -6,-1,DOWN |
    | -6,5,DOWN |
    | -6,6,DOWN |
    | -6,7,DOWN |
    | -6,8,DOWN |
    | -6,9,DOWN |
    | -5,-9,DOWN |
    | -5,-8,DOWN |
    | -5,-7,DOWN |
    | -5,-6,DOWN |
    | -5,-5,DOWN |
    | -5,-4,DOWN |
    | -5,-3,DOWN |
    | -5,-2,DOWN |
    | -5,-1,DOWN |
    | -5,5,DOWN |
    | -5,6,DOWN |
    | -5,7,DOWN |
    | -5,8,DOWN |
    | -5,9,DOWN |
    | -4,-9,DOWN |
    | -4,-8,DOWN |
    | -4,-7,DOWN |
    | -4,-6,DOWN |
    | -4,-5,DOWN |
    | -4,-4,DOWN |
    | -4,-3,DOWN |
    | -4,-2,DOWN |
    | -4,-1,DOWN |
    | -4,5,DOWN |
    | -4,6,DOWN |
    | -4,7,DOWN |
    | -4,8,DOWN |
    | -4,9,DOWN |
    | -3,-9,DOWN |
    | -3,-8,DOWN |
    | -3,-7,DOWN |
    | -3,-6,DOWN |
    | -3,-5,DOWN |
    | -3,-4,DOWN |
    | -3,-3,DOWN |
    | -3,-2,DOWN |
    | -3,-1,DOWN |
    | -3,5,DOWN |
    | -3,6,DOWN |
    | -3,7,DOWN |
    | -3,8,DOWN |
    | -3,9,DOWN |
    | -2,-9,DOWN |
    | -2,-8,DOWN |
    | -2,-7,DOWN |
    | -2,-6,DOWN |
    | -2,-5,DOWN |
    | -2,-4,DOWN |
    | -2,-3,DOWN |
    | -2,-2,DOWN |
    | -2,-1,DOWN |
    | -2,5,DOWN |
    | -2,6,DOWN |
    | -2,7,DOWN |
    | -2,8,DOWN |
    | -2,9,DOWN |
    | -1,-9,DOWN |
    | -1,-8,DOWN |
    | -1,-7,DOWN |
    | -1,-6,DOWN |
    | -1,-5,DOWN |
    | -1,-4,DOWN |
    | -1,-3,DOWN |
    | -1,-2,DOWN |
    | -1,-1,DOWN |
    | -1,5,DOWN |
    | -1,6,DOWN |
    | -1,7,DOWN |
    | -1,8,DOWN |
    | -1,9,DOWN |
    | 5,-9,DOWN |
    | 5,-8,DOWN |
    | 5,-7,DOWN |
    | 5,-6,DOWN |
    | 5,-5,DOWN |
    | 5,-4,DOWN |
    | 5,-3,DOWN |
    | 5,-2,DOWN |
    | 5,-1,DOWN |
    | 5,5,DOWN |
    | 5,6,DOWN |
    | 5,7,DOWN |
    | 5,8,DOWN |
    | 5,9,DOWN |
    | 6,-9,DOWN |
    | 6,-8,DOWN |
    | 6,-7,DOWN |
    | 6,-6,DOWN |
    | 6,-5,DOWN |
    | 6,-4,DOWN |
    | 6,-3,DOWN |
    | 6,-2,DOWN |
    | 6,-1,DOWN |
    | 6,5,DOWN |
    | 6,6,DOWN |
    | 6,7,DOWN |
    | 6,8,DOWN |
    | 6,9,DOWN |
    | 7,-9,DOWN |
    | 7,-8,DOWN |
    | 7,-7,DOWN |
    | 7,-6,DOWN |
    | 7,-5,DOWN |
    | 7,-4,DOWN |
    | 7,-3,DOWN |
    | 7,-2,DOWN |
    | 7,-1,DOWN |
    | 7,5,DOWN |
    | 7,6,DOWN |
    | 7,7,DOWN |
    | 7,8,DOWN |
    | 7,9,DOWN |
    | 8,-9,DOWN |
    | 8,-8,DOWN |
    | 8,-7,DOWN |
    | 8,-6,DOWN |
    | 8,-5,DOWN |
    | 8,-4,DOWN |
    | 8,-3,DOWN |
    | 8,-2,DOWN |
    | 8,-1,DOWN |
    | 8,5,DOWN |
    | 8,6,DOWN |
    | 8,7,DOWN |
    | 8,8,DOWN |
    | 8,9,DOWN |
    | 9,-9,DOWN |
    | 9,-8,DOWN |
    | 9,-7,DOWN |
    | 9,-6,DOWN |
    | 9,-5,DOWN |
    | 9,-4,DOWN |
    | 9,-3,DOWN |
    | 9,-2,DOWN |
    | 9,-1,DOWN |
    | 9,5,DOWN |
    | 9,6,DOWN |
    | 9,7,DOWN |
    | 9,8,DOWN |
    | 9,9,DOWN |

